// Code generated by rice embed-go; DO NOT EDIT.
package main

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "app.js",
		FileModTime: time.Unix(1572441411, 0),

		Content: string("document.getElementById(\"text\").innerHTML = \"hello world<br />created by TM</p>\";\n"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "custom.css",
		FileModTime: time.Unix(1572435829, 0),

		Content: string(".container {\r\n  width: 400px;\r\n  height: 100px;\r\n  background-color: #009ACD;\r\n  margin: auto;\r\n}\r\n\r\n.text {\r\n  position: relative;\r\n  top: 50%;\r\n  transform: translateY(-50%);\r\n  text-align: center;\r\n  color: #FFFFFF;\r\n\r\n}\r\n"),
	}
	file4 := &embedded.EmbeddedFile{
		Filename:    "index.html",
		FileModTime: time.Unix(1572436026, 0),

		Content: string("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Interval Timer</title>\r\n        <link rel=\"stylesheet\" href=\"custom.css\" />\r\n    </head>\r\n    <body>\r\n        <div class=\"container\">\r\n            <p id=\"text\" class=\"text\"></p>\r\n        </div>\r\n        <script src=\"app.js\"></script>\r\n    </body>\r\n</html>\r\n"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1572436645, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "app.js"
			file3, // "custom.css"
			file4, // "index.html"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`website`, &embedded.EmbeddedBox{
		Name: `website`,
		Time: time.Unix(1572436645, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"app.js":     file2,
			"custom.css": file3,
			"index.html": file4,
		},
	})
}
